package controller

import _ "embed"

//go:embed panel.css
var panelModernCSS string

const panelCSS = `
:root{font-family:ui-sans-serif,system-ui,sans-serif;color:#18202a;background:#f4f6f8}*{box-sizing:border-box}
body{margin:0}header{display:flex;align-items:center;justify-content:space-between;padding:18px 28px;background:#17212b;color:#fff}
main{max-width:1400px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:minmax(0,1fr);gap:20px}
section{background:#fff;border:1px solid #dce2e8;border-radius:8px;padding:18px;overflow:auto}h1,h2{margin:0 0 14px}h1{font-size:22px}h2{font-size:18px}
table{border-collapse:collapse;width:100%;font-size:13px}th,td{border-bottom:1px solid #e7ebef;padding:8px;text-align:left;vertical-align:top}th{color:#52606d}
form.inline{display:inline}form.stack{display:grid;grid-template-columns:repeat(2,minmax(120px,1fr));gap:8px;margin-top:14px}form.stack button{grid-column:1/-1}details{min-width:220px;margin-top:8px}details form{display:grid;gap:6px;margin:8px 0}summary{cursor:pointer;color:#1463d6}.danger{background:#b42318;border-color:#b42318}small{display:block;color:#687784;margin:6px 0}@media(max-width:600px){main{padding:10px}section{padding:10px}form.stack{grid-template-columns:minmax(0,1fr)}}
label{display:grid;gap:4px;font-size:12px;color:#52606d}input,select,button{font:inherit;padding:8px;border:1px solid #b9c3cc;border-radius:5px;background:#fff}button{cursor:pointer;background:#1463d6;color:#fff;border-color:#1463d6}.muted{color:#687784}.error{color:#b42318}.ok{color:#087443}.warning{padding:10px;border:1px solid #e6b44b;border-radius:5px;background:#fff6dc;color:#704b00}.login{max-width:360px;margin:15vh auto;background:#fff;padding:28px;border-radius:8px}.login form{display:grid;gap:14px}code{word-break:break-all}
`

var panelTemplate = `{{define "panel"}}<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>xmesh panel</title><style>` + panelCSS + panelModernCSS + `</style><script src="/assets/panel.js" defer></script></head><body>
<header><a class="brand" href="#overview">◈ <strong>XMesh</strong><span>CONTROL CENTER</span></a><h1 class="sr-only">xmesh control panel</h1><form class="inline" method="post" action="/logout"><button>退出登录</button></form></header>
<nav class="sidebar" aria-label="主导航"><a href="#overview">◉ <span>总览</span></a><a href="#network">⌘ <span>节点与线路</span></a><a href="#users">♙ <span>用户与订阅</span></a><a href="#deploy">↗ <span>部署向导</span></a><a href="#maintenance">⚙ <span>系统维护</span></a><p>Gateway → Agent<br>连接状态 · 配置 · 订阅</p></nav>
<main><div class="page-heading"><div><p class="eyebrow">XMESH / WORKSPACE</p><h1 id="page-title">总览</h1><p class="muted" id="page-description">查看网络健康状况与需要处理的事项。</p></div><div class="refresh-tools"><button type="button" id="refresh-status">刷新状态</button><span id="refresh-note" role="status">正在获取状态…</span></div></div><div id="stale-banner" role="alert" hidden></div>
{{if .InsecurePublicURL}}<div id="transport-warning" role="alert">警告：Controller 的 public_url 使用 HTTP。管理登录、节点注册和订阅链接在公网传输时可能泄露；请为对外地址启用 HTTPS。</div>{{end}}<div id="notice" role="status">{{if .Notice}}{{.Notice}}{{end}}</div><noscript><p>启用 JavaScript 可使用拓扑、筛选及局部刷新。下方基础管理表单仍可使用。</p></noscript><div class="grid">
<section id="overview" data-page="overview"><div id="metrics" class="metrics"><p>正在加载网络状态…</p></div></section>
<section id="network-map" data-page="overview"><div class="section-heading"><div><h2>网络连接</h2><p class="muted">选择节点或线路查看详情。Gateway 与 Agent 线路需两端配置和链路就绪；外部出口的连通性需用实际流量验证。</p></div><div class="segmented"><button type="button" data-view="topology" aria-pressed="true">拓扑</button><button type="button" data-view="matrix" aria-pressed="false">矩阵</button></div></div><div class="toolbar"><label>搜索节点<input id="map-search" type="search" placeholder="名称或地址"></label><label>线路状态<select id="map-state"><option value="all">全部状态</option><option value="ready">可用</option><option value="configured">已配置，待验证</option><option value="pending">待就绪</option><option value="offline">离线</option><option value="disabled">停用</option></select></label></div><div id="topology"></div><div id="matrix" hidden></div><p class="legend">● 可用　◐ 待就绪　◌ 已配置待验证　○ 离线　— 停用 · Agent 主动建立隧道</p></section>
<section id="attention" data-page="overview"><h2>需要处理</h2><div id="todo-list" class="todo-list"></div></section>
<section id="trends" data-page="overview"><div class="section-heading"><div><h2>链路趋势</h2><p class="muted">最近 24 小时 · 每 5 分钟采样 · Gateway 单端统计</p></div><label>链路<select id="history-link" aria-label="历史链路"></select></label></div><div id="history-chart"></div><div id="rankings"></div></section>
<section id="wizard" data-page="deploy"><p class="eyebrow">部署向导</p><h2>从节点到可用订阅</h2><p>先选择要添加的对象。单独添加节点后，还需安装并绑定线路，才能授权用户使用。</p><div class="wizard-choices"><a href="#create-route"><strong>新建完整线路</strong><span>同时创建 Gateway、Agent 与 Link</span></a><a href="#wizard-gateway"><strong>添加 Gateway</strong><span>创建公网入口，再连接已有 Agent</span></a><a href="#wizard-agent"><strong>添加 Agent</strong><span>创建网络出口，再连接已有 Gateway</span></a><a href="#assign"><strong>复用已有节点</strong><span>为 Agent 绑定一个或多个 Gateway</span></a></div><ol class="wizard-steps"><li><a href="#create-route">1. 创建节点或线路</a></li><li><a href="#quick-install">2. 安装节点</a></li><li><a href="#assign">3. 绑定线路</a></li><li><a href="#readiness">4. 检查就绪</a></li><li><a href="#subscribe">5. 授权用户</a></li></ol><div id="deployment-progress"></div></section>
<section id="create-route" data-page="deploy"><h2>新建完整线路</h2><p class="muted">REALITY Link URL 使用 Gateway 可访问的地址，target 填写 Gateway 可访问的 HTTPS 站点。默认监听 8443 端口；旧版 WSS 线路仍受支持。</p><form class="stack" method="post" action="/admin/quick-setup"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Gateway 名称<input name="gateway_name" required></label><label>Agent 名称<input name="agent_name" required></label><label>Gateway 公网地址<input name="public_host" placeholder="gateway.example.com" required></label><label>Gateway 所在地<select name="region"><option value="">未设置 / 手动填写 target</option><option value="cn">中国国内 · api.bilibili.com:443</option><option value="overseas">境外 · www.swift.com:443</option></select></label><label>VMess 端口<input type="number" name="vmess_port" value="8080" min="1" max="65535" required></label><label>WebSocket 路径<input name="vmess_path" value="/proxy" required></label><label>VMess HTTP Host<input name="vmess_host"></label><label>Agent 允许访问的 CIDR<input name="allowed_cidrs" value="0.0.0.0/0, ::/0" required></label><label>Agent 拒绝访问的 CIDR<input name="denied_cidrs" placeholder="169.254.0.0/16"></label><label>Agent → Gateway Link URL<input name="link_url" placeholder="reality://203.0.113.10:8443/tunnel" required></label><label>REALITY target (for reality://)<input name="reality_target" placeholder="example.com:443"></label><label>Link HTTP Host<input name="link_http_host"></label><label>Link TLS server name (legacy WSS)<input name="tls_server_name"></label><button>创建线路</button></form></section>
<section id="wizard-gateway" data-page="deploy"><h2>单独添加 Gateway</h2><p class="muted">创建公网入口后，在对应主机安装 Gateway，再选择已有 Agent 建立线路。未绑定时会显示为“节点已创建，尚无可用线路”。</p><form class="stack" method="post" action="/admin/gateways"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Gateway 名称<input name="name" required></label><label>公网地址<input name="public_host" placeholder="gateway.example.com" required></label><label>Gateway 所在地<select name="region"><option value="">未设置，绑定时手动填写 REALITY target</option><option value="cn">中国国内 · api.bilibili.com:443</option><option value="overseas">境外 · www.swift.com:443</option></select></label><label>VMess 端口<input type="number" name="vmess_port" value="8080" min="1" max="65535"></label><label>WebSocket 路径<input name="vmess_path" value="/proxy"></label><label>HTTP Host<input name="vmess_host"></label><button>创建 Gateway</button></form><p class="next-steps">创建后：<a href="#quick-install">安装 Gateway</a> → <a href="#assign">连接已有 Agent</a> → <a href="#readiness">检查线路</a> → <a href="#subscribe">授权用户</a></p></section>
<section id="wizard-agent" data-page="deploy"><h2>单独添加 Agent</h2><p class="muted">创建网络出口后，在对应主机安装 Agent，再将它连接到一个或多个已有 Gateway。未绑定时会显示为“节点已创建，尚无可用线路”。</p><form class="stack" method="post" action="/admin/agents"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Agent 名称<input name="name" required></label><label>允许访问的 CIDR<input name="allowed_cidrs" value="0.0.0.0/0, ::/0" required></label><label>拒绝访问的 CIDR<input name="denied_cidrs" placeholder="169.254.0.0/16"></label><button>创建 Agent</button></form><p class="next-steps">创建后：<a href="#quick-install">安装 Agent</a> → <a href="#assign">连接已有 Gateway</a> → <a href="#readiness">检查线路</a> → <a href="#subscribe">授权用户</a></p></section>
<section id="quick-install" data-page="deploy"><h2>按节点生成安装命令</h2><p class="muted">先添加 Gateway 或 Agent，再在对应主机运行安装命令并输入一次性令牌。节点可以先安装，稍后再绑定线路。</p>{{range .GatewayList}}<form class="inline" method="post" action="/admin/enrollments"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="role" value="gateway"><input type="hidden" name="node_id" value="{{.ID}}"><button>安装 Gateway：{{.Name}}</button></form> {{end}}{{range .AgentList}}<form class="inline" method="post" action="/admin/enrollments"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="role" value="agent"><input type="hidden" name="node_id" value="{{.ID}}"><button>安装 Agent：{{.Name}}</button></form> {{end}}</section>
<section id="install" data-page="deploy"><h2>最近生成的注册令牌</h2><p class="muted">一次性令牌只显示一次，30 分钟后过期。重新生成会撤销该节点旧的未使用令牌。</p><table><thead><tr><th>节点</th><th>状态</th><th>过期时间</th><th>操作</th></tr></thead><tbody>{{range .Enrollments}}<tr><td>{{.Role}} <code>{{.NodeID}}</code></td><td>{{.State}}</td><td>{{.ExpiresAt}}</td><td>{{if eq .State "active"}}<form class="inline" method="post" action="/admin/enrollments/{{.ID}}/revoke"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button class="secondary">撤销</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="4">暂无安装令牌。</td></tr>{{end}}</tbody></table></section>
<section id="assign" data-page="deploy"><h2>连接已有节点</h2><p class="muted">选择要连接的 Gateway。已有 target 保持不变；新 Gateway 根据各自所在地默认使用 api.bilibili.com:443（中国国内）或 www.swift.com:443（境外）。也可在下方手动覆盖新 target。未设置所在地时需手动填写。</p><form class="stack" method="post" action="/admin/assign-gateways"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Agent<select name="agent_id" required>{{range .AgentList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><fieldset><legend>Gateway</legend>{{range .GatewayList}}<label><input type="checkbox" name="gateway_id" value="{{.ID}}">{{.Name}} ({{.PublicHost}})</label>{{end}}</fieldset><label>新 Gateway 的 REALITY target<input name="reality_target" placeholder="留空：按各 Gateway 所在地使用默认值"></label><button>连接所选 Gateway</button></form></section>
<section id="readiness" data-page="deploy"><h2>检查节点与线路</h2><p class="muted">按顺序检查安装、在线、配置应用和线路就绪；节点在线不等于线路可用。</p><table><thead><tr><th>节点</th><th>版本</th><th>注册</th><th>在线</th><th>配置应用</th><th>运行就绪</th><th>下一步</th></tr></thead><tbody>{{range .Deployments}}<tr><td>{{.Role}} {{.Name}}<br><code>{{.ID}}</code></td><td>{{.Version}}</td><td>{{.Identity}}</td><td>{{.Online}}</td><td>{{.Applied}}</td><td>{{.Runtime}}</td><td>{{.Next}}</td></tr>{{else}}<tr><td colspan="7">先添加 Gateway 或 Agent 节点。</td></tr>{{end}}</tbody></table></section>
<section id="activity" data-page="maintenance"><h2>操作记录</h2><p class="muted">最近 100 次管理请求的执行结果。节点就绪与升级完成情况会单独跟踪。</p><div id="upgrade-progress"></div><div id="operation-list"></div></section>
<section id="node-upgrades" data-page="maintenance"><h2>节点升级</h2><p class="muted">升级助手在宿主机主动领取任务。批量任务按所选顺序逐台执行，失败时暂停。目标版本使用已发布的固定版本。</p><form class="stack" method="post" action="/admin/upgrades"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>目标版本<input name="version" value="{{.Release.Version}}" required pattern="v[A-Za-z0-9._-]+"></label><fieldset><legend>选择节点（按显示顺序）</legend>{{range .GatewayList}}<label data-links="{{(index $.NodeImpacts .ID).Links}}" data-users="{{(index $.NodeImpacts .ID).Users}}"><input type="checkbox" name="node_id" value="{{.ID}}">Gateway {{.Name}} · {{(index $.UpgraderViews .ID).State}} · {{(index $.NodeStatus .ID).BinaryVersion}} · {{(index $.NodeImpacts .ID).Links}} Links / {{(index $.NodeImpacts .ID).Users}} users</label>{{end}}{{range .AgentList}}<label data-links="{{(index $.NodeImpacts .ID).Links}}" data-users="{{(index $.NodeImpacts .ID).Users}}"><input type="checkbox" name="node_id" value="{{.ID}}">Agent {{.Name}} · {{(index $.UpgraderViews .ID).State}} · {{(index $.NodeStatus .ID).BinaryVersion}} · {{(index $.NodeImpacts .ID).Links}} Links / {{(index $.NodeImpacts .ID).Users}} users</label>{{end}}</fieldset><button>创建升级任务</button></form><h3>助手与迁移</h3><table><thead><tr><th>节点</th><th>助手</th><th>操作</th></tr></thead><tbody>{{range .GatewayList}}<tr><td>Gateway {{.Name}}</td><td>{{(index $.UpgraderViews .ID).State}} · {{(index $.UpgraderViews .ID).Mode}}/{{(index $.UpgraderViews .ID).Arch}} · 节点 {{(index $.NodeStatus .ID).BinaryVersion}} · 升级助手 {{(index $.UpgraderViews .ID).Version}}</td><td><form method="post" action="/admin/updaters/gateway/{{.ID}}/pair"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>生成配对令牌</button></form></td></tr>{{end}}{{range .AgentList}}<tr><td>Agent {{.Name}}</td><td>{{(index $.UpgraderViews .ID).State}} · {{(index $.UpgraderViews .ID).Mode}}/{{(index $.UpgraderViews .ID).Arch}} · 节点 {{(index $.NodeStatus .ID).BinaryVersion}} · 升级助手 {{(index $.UpgraderViews .ID).Version}}</td><td><form method="post" action="/admin/updaters/agent/{{.ID}}/pair"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>生成配对令牌</button></form></td></tr>{{end}}</tbody></table><h3>升级记录</h3><table><thead><tr><th>节点</th><th>版本</th><th>阶段</th><th>结果</th><th>操作</th></tr></thead><tbody>{{range .UpgradeTaskList}}<tr><td>{{.Role}} <code>{{.NodeID}}</code></td><td>{{.FromVersion}} → {{.TargetVersion}}</td><td>{{.Stage}}<br><small>{{.UpdatedAt}}</small></td><td><span class="error">{{.Error}}</span></td><td>{{if or (eq .Stage "pending") (eq .Stage "preparing")}}<form method="post" action="/admin/upgrades/{{.ID}}/cancel"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>取消</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="5">暂无升级任务</td></tr>{{end}}</tbody></table></section>
<section id="release" data-page="maintenance"><h2>发布源与安装文件</h2><p>版本 <code>{{.Release.Version}}</code> · GitHub：<code>{{.Release.GitHubURL}}</code></p><p>Controller 镜像：<code>{{.Release.LocalURL}}</code> · {{if .Release.Ready}}全部已缓存{{else}}尚未全部缓存{{end}}</p><p class="muted">首次下载时 Controller 从 GitHub 获取文件、校验 SHA256SUMS，并缓存在磁盘供后续节点使用。Controller 本身不包含发布二进制文件。</p><table><thead><tr><th>文件</th><th>已缓存并校验</th></tr></thead><tbody>{{range .Release.Assets}}<tr><td><a href="{{$.Release.LocalURL}}/{{.Name}}">{{.Name}}</a></td><td>{{if .Ready}}已缓存{{else}}未缓存{{end}}</td></tr>{{end}}</tbody></table>{{if not .Release.Enabled}}<p class="error">请在 Controller 配置中设置 release_dir、release_base_url（HTTPS）和 release_version 以启用缓存。</p>{{end}}</section>



<section id="users" data-page="users"><h2>用户</h2><table><thead><tr><th>用户</th><th>状态</th><th>操作</th></tr></thead><tbody>{{range .UserList}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td>{{if .Enabled}}启用{{else}}停用{{end}}</td><td><form class="inline" method="post" action="/admin/users/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button class="secondary">{{if .Enabled}}停用{{else}}启用{{end}}</button></form><details><summary>重置订阅链接</summary><p>旧链接会立即失效，使用旧链接的客户端需要更新。</p><form method="post" action="/admin/users/{{.ID}}/reset-subscription"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button class="danger">确认重置</button></form></details></td></tr>{{else}}<tr><td colspan="3">暂无用户</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/users"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>名称<input name="name" required></label><button>创建用户</button></form></section>

<section id="routes" data-page="network"><div class="section-heading"><div><h2>线路总览</h2><p class="muted">先查看入口到出口的状态，再进入对应节点或 Link 调整配置。</p></div><a href="#create-route">新建线路</a></div><div class="network-shortcuts"><a href="#gateways">Gateway</a><a href="#agents">Agent</a><a href="#upstreams">外部出口</a><a href="#assignments">节点组合</a><a href="#links">Link</a></div><div class="toolbar"><label>搜索线路<input id="route-search" type="search" placeholder="入口或出口名称"></label><label>状态<select id="route-state"><option value="all">全部状态</option><option value="ready">可用</option><option value="configured">已配置，待验证</option><option value="pending">待就绪</option><option value="offline">离线</option><option value="disabled">停用</option></select></label></div><div id="route-overview"><p>正在加载线路…</p></div></section>
<section id="gateways" data-page="network"><h2>Gateway 节点</h2><table><thead><tr><th>Gateway</th><th>VMess WS</th><th>配置</th><th>运行状态</th><th>操作</th></tr></thead><tbody>{{range .GatewayList}}{{$st := index $.NodeStatus .ID}}{{$impact := index $.NodeImpacts .ID}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td>{{.PublicHost}}:{{.VMessPort}}{{.VMessPath}}<br>TLS 未启用</td><td>{{if .Enabled}}启用{{else}}停用{{end}}<br>目标配置 {{.DesiredVersion}}<br>{{status $st.AppliedVersion .DesiredVersion $st.ApplyError}}<br>Xray {{if $st.XrayReady}}就绪{{else}}未就绪{{end}}</td><td>{{if $st.Online}}在线{{else}}离线{{end}}，{{if $st.Ready}}就绪{{else}}未就绪{{end}}<br>隧道 {{$st.TunnelConnections}}, TCP {{$st.TCPConnections}}, UDP {{$st.UDPAssociations}}<br><span class="error">{{$st.LastError}}</span></td><td><form class="inline" method="post" action="/admin/gateways/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button class="secondary">{{if .Enabled}}停用{{else}}启用{{end}}</button></form><details><summary>编辑与删除</summary><form method="post" action="/admin/gateways/{{.ID}}/edit"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>名称<input name="name" value="{{.Name}}" required></label><label>公网地址<input name="public_host" value="{{.PublicHost}}" required></label><label>Gateway 所在地<select name="region"><option value="">未设置 / 手动填写 target</option><option value="cn" {{if eq .Region "cn"}}selected{{end}}>中国国内 · api.bilibili.com:443</option><option value="overseas" {{if eq .Region "overseas"}}selected{{end}}>境外 · www.swift.com:443</option></select></label><small>所在地仅用于新 target 默认值，不会修改已经运行的 REALITY target。</small><label>VMess 端口<input type="number" name="vmess_port" value="{{.VMessPort}}" min="1" max="65535" required></label><label>WebSocket 路径<input name="vmess_path" value="{{.VMessPath}}" required></label><label>HTTP Host<input name="vmess_host" value="{{.VMessHost}}"></label><button>保存</button></form><small>Gateway 确认应用新配置后，访问权限变更才会发布。自动生成的 REALITY Link 地址会随公网地址更新。</small><p>删除影响：{{$impact.Assignments}} 个节点组合、{{$impact.Links}} 条 Link、{{$impact.Grants}} 项授权，涉及 {{$impact.Users}} 位用户。</p><form method="post" action="/admin/gateways/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>输入 Gateway 名称以确认删除<input name="confirm_name" required autocomplete="off"></label><button class="danger">删除 Gateway 及线路</button></form><small>已安装的节点需另行停止。</small></details></td></tr>{{else}}<tr><td colspan="5">暂无 Gateway 节点</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/gateways"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>名称<input name="name" required></label><label>公网地址<input name="public_host" required></label><label>Gateway 所在地<select name="region"><option value="">未设置 / 手动填写 target</option><option value="cn">中国国内 · api.bilibili.com:443</option><option value="overseas">境外 · www.swift.com:443</option></select></label><label>VMess 端口<input type="number" name="vmess_port" value="8080" min="1" max="65535"></label><label>WebSocket 路径<input name="vmess_path" value="/proxy"></label><label>HTTP Host<input name="vmess_host"></label><button>创建 Gateway</button></form></section>

<section id="agents" data-page="network"><h2>Agent 节点</h2><table><thead><tr><th>Agent</th><th>配置</th><th>运行状态</th><th>操作</th></tr></thead><tbody>{{range .AgentList}}{{$st := index $.NodeStatus .ID}}{{$impact := index $.NodeImpacts .ID}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td>{{if .Enabled}}启用{{else}}停用{{end}}<br>目标配置 {{.DesiredVersion}}<br>{{status $st.AppliedVersion .DesiredVersion $st.ApplyError}}</td><td>{{if $st.Online}}在线{{else}}离线{{end}}，{{if $st.Ready}}就绪{{else}}未就绪{{end}}<br>隧道 {{$st.TunnelConnections}}, TCP {{$st.TCPConnections}}, UDP {{$st.UDPAssociations}}<br><span class="error">{{$st.LastError}}</span></td><td><form class="inline" method="post" action="/admin/agents/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button class="secondary">{{if .Enabled}}停用{{else}}启用{{end}}</button></form><details><summary>编辑与删除</summary><form method="post" action="/admin/agents/{{.ID}}/edit"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>名称<input name="name" value="{{.Name}}" required></label><label>允许访问的 CIDR<input name="allowed_cidrs" value="{{join .AllowedCIDRs}}" required></label><label>拒绝访问的 CIDR<input name="denied_cidrs" value="{{join .DeniedCIDRs}}"></label><button>保存</button></form><p>删除影响：{{$impact.Assignments}} 个节点组合、{{$impact.Links}} 条 Link、{{$impact.Grants}} 项授权，涉及 {{$impact.Users}} 位用户。</p><form method="post" action="/admin/agents/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>输入 Agent 名称以确认删除<input name="confirm_name" required autocomplete="off"></label><button class="danger">删除 Agent 及线路</button></form><small>已安装的节点需另行停止。</small></details></td></tr>{{else}}<tr><td colspan="4">暂无 Agent 节点</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/agents"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>名称<input name="name" required></label><label>允许访问的 CIDR<input name="allowed_cidrs" value="0.0.0.0/0, ::/0" required></label><label>拒绝访问的 CIDR<input name="denied_cidrs" placeholder="169.254.0.0/16"></label><button>创建 Agent</button></form></section>

<section id="assignments" data-page="network"><h2>Gateway / Agent 线路</h2><table><thead><tr><th>线路组合 ID</th><th>Gateway</th><th>Agent</th><th>状态</th><th>操作</th></tr></thead><tbody>{{range .AttachmentList}}{{$impact := index $.RouteImpacts .ID}}<tr><td><code>{{.ID}}</code></td><td>{{(index $.Gateways .GatewayID).Name}}</td><td>{{(index $.Agents .AgentID).Name}}</td><td>{{if .Enabled}}启用{{else}}停用{{end}}</td><td><form class="inline" method="post" action="/admin/attachments/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button class="secondary">{{if .Enabled}}停用{{else}}启用{{end}}</button></form><details><summary>删除</summary><p>将删除 {{$impact.Links}} 条 Link 和 {{$impact.Grants}} 项授权，影响 {{$impact.Users}} 位用户。</p><form method="post" action="/admin/attachments/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>输入节点组合 ID 以确认删除<input name="confirm_id" required autocomplete="off"></label><button class="danger">删除节点组合</button></form></details></td></tr>{{else}}<tr><td colspan="5">暂无节点组合</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/attachments"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Gateway<select name="gateway_id" required>{{range .GatewayList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><label>Agent<select name="agent_id" required>{{range .AgentList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><button>创建节点组合</button></form></section>

<section id="links" data-page="network"><h2>Link 链路</h2><table><thead><tr><th>Link</th><th>线路</th><th>策略</th><th>状态</th><th>操作</th></tr></thead><tbody>{{range .LinkList}}{{$st := index $.LinkSummary .ID}}{{$route := index $.Attachments .AttachmentID}}{{$gw := index $.Gateways $route.GatewayID}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td><code>{{.URL}}</code><br>线路组合 {{short .AttachmentID}}</td><td><form method="post" action="/admin/links/{{.ID}}/policy"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="number" name="priority" value="{{.Priority}}" min="0" title="priority"><input type="number" name="weight" value="{{.Weight}}" min="1" title="weight"><input type="number" name="connections" value="{{.Connections}}" min="1" title="connections"><input type="number" name="max_streams" value="{{.MaxStreams}}" min="1" title="max streams"><button>应用策略</button></form></td><td>{{if $st.Online}}在线{{else}}离线{{end}}，{{if $st.Ready}}就绪{{else}}未就绪{{end}}<br>连接 {{$st.Connections}}，流 {{$st.ActiveStreams}}, RTT {{$st.RTTMillis}} ms<br>写入停顿 {{$st.WriteStalls}}，阻塞 {{$st.WriteBlockedMillis}} ms，拒绝 {{$st.QueueDrops}}<br>↑ {{$st.UploadBytes}} ↓ {{$st.DownloadBytes}}<br><span class="error">{{$st.LastError}}</span></td><td>{{if .Enabled}}启用{{else}}停用{{end}}<br><form class="inline" method="post" action="/admin/links/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button class="secondary">{{if .Enabled}}停用{{else}}启用{{end}}</button></form><details><summary>编辑与删除</summary><form method="post" action="/admin/links/{{.ID}}/edit"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>名称<input name="name" value="{{.Name}}" required></label><label>Link URL<input name="url" value="{{.URL}}" required></label><label>REALITY target (shared by Gateway)<input name="reality_target" value="{{$gw.RealityTarget}}"></label><label>HTTP Host<input name="http_host" value="{{.HTTPHost}}"></label><label>TLS server name (legacy WSS)<input name="tls_server_name" value="{{.TLSServerName}}"></label><label>TLS verify (legacy WSS)<input type="checkbox" name="tls_verify" {{if .TLSVerify}}checked{{end}}></label><button>保存 Link</button></form><small>修改共享的 REALITY target 后，此 Gateway 的所有 Link 都会在节点应用配置后更新。</small><form method="post" action="/admin/links/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>输入 Link 名称以确认删除<input name="confirm_name" required autocomplete="off"></label><button class="danger">删除 Link</button></form></details></td></tr>{{else}}<tr><td colspan="5">暂无 Link</td></tr>{{end}}</tbody></table>
<h3>节点上报</h3><table><thead><tr><th>Link</th><th>上报节点</th><th>连接数</th><th>最近上报</th></tr></thead><tbody>{{range .LinkReports}}<tr><td><code>{{short .LinkID}}</code></td><td><code>{{short .ReporterNodeID}}</code></td><td>{{.Connections}} / 活跃流 {{.ActiveStreams}}</td><td><time datetime="{{.LastSeen.Format "2006-01-02T15:04:05Z07:00"}}">{{.LastSeen.Format "2006-01-02 15:04:05 MST"}}</time><br><span class="error">{{.LastError}}</span></td></tr>{{else}}<tr><td colspan="4">暂无运行上报</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/links"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>节点<select name="attachment_id" required>{{range .AttachmentList}}<option value="{{.ID}}">{{(index $.Gateways .GatewayID).Name}} / {{(index $.Agents .AgentID).Name}}</option>{{end}}</select></label><label>名称<input name="name" required></label><label>Link URL<input name="url" placeholder="reality://203.0.113.10:8443/tunnel" required></label><label>REALITY target (for reality://)<input name="reality_target" placeholder="example.com:443"></label><label>HTTP Host<input name="http_host"></label><label>TLS server name (legacy WSS)<input name="tls_server_name"></label><label>TLS verify (legacy WSS)<input type="checkbox" name="tls_verify" checked></label><label>Priority<input type="number" name="priority" value="10" min="0"></label><label>Weight<input type="number" name="weight" value="1" min="1"></label><label>Connections<input type="number" name="connections" value="2" min="1"></label><label>Max streams/session<input type="number" name="max_streams" value="256" min="1"></label><button>创建 Link</button></form></section>

<section id="usage" data-page="users"><h2>用户流量</h2><p class="muted">按 Gateway 实际转发的有效载荷统计，上传/下载分别显示；仅包含升级到本版本后采集的流量，保留最近 30 天。时间窗口按 5 分钟采样桶统计。</p><div id="usage-table"><p>正在加载流量统计…</p></div></section>
<section id="grants" data-page="users"><h2>授权管理</h2><p class="muted">在这里管理用户可使用的节点组合；上方按用户和实际 Link 查看用量。</p><details><summary>查看授权记录与管理操作</summary><table id="grant-table"><thead><tr><th>授权</th><th>用户</th><th>节点</th><th>状态</th><th>流量 / 连接</th><th>操作</th></tr></thead><tbody>{{range .GrantList}}{{$st := index $.GrantSummary .ID}}<tr><td><code>{{.ID}}</code><br>UUID {{.VMessUUID}}</td><td>{{(index $.Users .UserID).Name}}</td><td><code>{{short .AttachmentID}}</code></td><td>{{if .Enabled}}启用{{else}}停用{{end}}<br>{{if .Published}}已发布{{else}}待发布{{end}}</td><td>↑ {{$st.UploadBytes}} ↓ {{$st.DownloadBytes}}<br>TCP {{$st.TCPConnections}}, UDP {{$st.UDPAssociations}}</td><td><form class="inline" method="post" action="/admin/grants/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button class="secondary">{{if .Enabled}}停用{{else}}启用{{end}}</button></form><details><summary>删除</summary><form method="post" action="/admin/grants/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>输入授权 ID 以确认删除<input name="confirm_id" required autocomplete="off"></label><button class="danger">删除授权</button></form></details></td></tr>{{else}}<tr><td colspan="6">暂无授权</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/grants"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>用户<select name="user_id" required>{{range .UserList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><label>节点<select name="attachment_id" required>{{range .AttachmentList}}<option value="{{.ID}}">{{(index $.Gateways .GatewayID).Name}} / {{(index $.Agents .AgentID).Name}}</option>{{end}}</select></label><button>创建授权</button></form></details></section>




<section id="subscribe" data-page="users"><h2>开通用户订阅</h2><p class="muted">在这里统一授权 Gateway / Agent 线路和外部出口线路。清除选择不会撤销已有授权；撤销请在授权管理中操作。Gateway 应用配置后自动发布订阅。</p><form class="stack" method="post" action="/admin/subscribe"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>用户<select name="user_id" required>{{range .UserList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><fieldset><legend>可授权线路</legend>{{range .AttachmentList}}<label><input type="checkbox" name="attachment_id" value="{{.ID}}">{{(index $.Gateways .GatewayID).Name}} / {{(index $.Agents .AgentID).Name}} · Agent</label>{{end}}{{range .ExternalAttachmentList}}<label><input type="checkbox" name="attachment_id" value="{{.ID}}">{{(index $.Gateways .GatewayID).Name}} / {{(index $.Upstreams .UpstreamID).Name}} · 外部出口</label>{{end}}</fieldset><button>开通所选线路</button></form>{{range .UserList}}<div class="subscription-row" data-user-id="{{.ID}}"><span class="publication">{{.Name}}（{{index $.SubscriptionCounts .ID}}）</span><button type="button" data-copy="{{$.PublicURL}}/subscription/{{.SubscriptionToken}}">复制订阅链接</button><details><summary>查看完整链接</summary><input aria-label="{{.Name}} 的订阅链接" value="{{$.PublicURL}}/subscription/{{.SubscriptionToken}}" readonly></details></div>{{end}}</section>

<section id="upgrade" data-page="maintenance"><h2>升级与备份</h2><p class="muted">升级命令使用配置的固定版本并保留节点身份。请在原主机执行；Docker 新容器启动失败时会回滚。</p><h3>Controller</h3>{{if .ControllerUpgrade.Ready}}<p>当前版本：{{.Release.Version}}。最近升级：{{if .ControllerUpgrade.State}}{{.ControllerUpgrade.State}} {{.ControllerUpgrade.Version}} {{.ControllerUpgrade.At}}{{else}}无{{end}}。</p><form method="post" action="/admin/controller/upgrade-latest"><input type="hidden" name="csrf" value="{{.CSRF}}"><button{{if or (eq .ControllerUpgrade.State "queued") (eq .ControllerUpgrade.State "running")}} disabled{{end}}>检查 GitHub 并升级 Controller</button></form><p class="muted">宿主机升级助手会校验 GitHub 发布文件、备份 Controller 状态，并在启动失败时回滚。升级期间面板会短暂断开。</p>{{else}}<p class="muted">一键升级需要 systemd 主机上的 Docker 安装，并安装 v0.2.3 或更新版本提供的宿主机升级助手。此前请在 Controller 主机运行已验证的安装命令。</p>{{end}}<p class="muted">Controller 备份含有凭据，请异地保存。</p><h3>节点</h3>{{range .GatewayList}}<p><a href="/admin/upgrade/gateway/{{.ID}}">升级 Gateway：{{.Name}}</a></p>{{end}}{{range .AgentList}}<p><a href="/admin/upgrade/agent/{{.ID}}">升级 Agent：{{.Name}}</a></p>{{end}}</section>

</div></main><dialog id="detail-dialog"><div class="section-heading"><h2 id="detail-title">详情</h2><button type="button" id="close-detail">关闭</button></div><div id="detail-body"></div></dialog></body></html>{{end}}`
