package controller

const panelCSS = `
:root{font-family:ui-sans-serif,system-ui,sans-serif;color:#18202a;background:#f4f6f8}*{box-sizing:border-box}
body{margin:0}header{display:flex;align-items:center;justify-content:space-between;padding:18px 28px;background:#17212b;color:#fff}
main{max-width:1400px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(440px,1fr));gap:20px}
section{background:#fff;border:1px solid #dce2e8;border-radius:8px;padding:18px;overflow:auto}h1,h2{margin:0 0 14px}h1{font-size:22px}h2{font-size:18px}
table{border-collapse:collapse;width:100%;font-size:13px}th,td{border-bottom:1px solid #e7ebef;padding:8px;text-align:left;vertical-align:top}th{color:#52606d}
form.inline{display:inline}form.stack{display:grid;grid-template-columns:repeat(2,minmax(120px,1fr));gap:8px;margin-top:14px}form.stack button{grid-column:1/-1}
label{display:grid;gap:4px;font-size:12px;color:#52606d}input,select,button{font:inherit;padding:8px;border:1px solid #b9c3cc;border-radius:5px;background:#fff}button{cursor:pointer;background:#1463d6;color:#fff;border-color:#1463d6}.muted{color:#687784}.error{color:#b42318}.ok{color:#087443}.login{max-width:360px;margin:15vh auto;background:#fff;padding:28px;border-radius:8px}.login form{display:grid;gap:14px}code{word-break:break-all}
`

const panelTemplate = `{{define "panel"}}<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>xmesh panel</title><style>` + panelCSS + `</style></head><body>
<header><h1>xmesh control panel</h1><form class="inline" method="post" action="/logout"><button>Sign out</button></form></header>
<main><p class="muted">Desired state revision {{.Revision}}. Runtime status is reported independently by each node.</p><div class="grid">

<section><h2>Users</h2><table><thead><tr><th>User</th><th>Enabled</th><th>Subscription</th><th>Action</th></tr></thead><tbody>{{range .Users}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td>{{.Enabled}}</td><td><code>{{$.PublicURL}}/subscription/{{.SubscriptionToken}}</code></td><td><form class="inline" method="post" action="/admin/users/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>Toggle</button></form> <form class="inline" method="post" action="/admin/users/{{.ID}}/reset-subscription"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>Reset link</button></form></td></tr>{{else}}<tr><td colspan="4">No users</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/users"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Name<input name="name" required></label><button>Create user</button></form></section>

<section><h2>Gateways</h2><table><thead><tr><th>Gateway</th><th>VMess WS</th><th>Config</th><th>Runtime</th><th>Action</th></tr></thead><tbody>{{range .Gateways}}{{$st := index $.NodeStatus .ID}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td>{{.PublicHost}}:{{.VMessPort}}{{.VMessPath}}<br>TLS off</td><td>enabled {{.Enabled}}<br>desired {{.DesiredVersion}}<br>{{status $st.AppliedVersion .DesiredVersion $st.ApplyError}}<br>Xray ready: {{$st.XrayReady}}</td><td>online {{$st.Online}}, ready {{$st.Ready}}<br>tunnels {{$st.TunnelConnections}}, TCP {{$st.TCPConnections}}, UDP {{$st.UDPAssociations}}<br><span class="error">{{$st.LastError}}</span></td><td><form class="inline" method="post" action="/admin/gateways/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>Toggle</button></form></td></tr>{{else}}<tr><td colspan="5">No gateways</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/gateways"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Name<input name="name" required></label><label>Public host<input name="public_host" required></label><label>VMess port<input type="number" name="vmess_port" value="8080" min="1" max="65535"></label><label>WS path<input name="vmess_path" value="/proxy"></label><label>HTTP Host<input name="vmess_host"></label><button>Create gateway</button></form></section>

<section><h2>Agents</h2><table><thead><tr><th>Agent</th><th>Config</th><th>Runtime</th><th>Action</th></tr></thead><tbody>{{range .Agents}}{{$st := index $.NodeStatus .ID}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td>enabled {{.Enabled}}<br>desired {{.DesiredVersion}}<br>{{status $st.AppliedVersion .DesiredVersion $st.ApplyError}}</td><td>online {{$st.Online}}, ready {{$st.Ready}}<br>tunnels {{$st.TunnelConnections}}, TCP {{$st.TCPConnections}}, UDP {{$st.UDPAssociations}}<br><span class="error">{{$st.LastError}}</span></td><td><form class="inline" method="post" action="/admin/agents/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>Toggle</button></form></td></tr>{{else}}<tr><td colspan="4">No agents</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/agents"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Name<input name="name" required></label><label>Allowed CIDRs<input name="allowed_cidrs" value="0.0.0.0/0, ::/0" required></label><label>Denied CIDRs<input name="denied_cidrs" placeholder="169.254.0.0/16"></label><button>Create agent</button></form></section>

<section><h2>Gateway × Agent nodes</h2><table><thead><tr><th>Node ID</th><th>Gateway</th><th>Agent</th><th>Enabled</th><th>Action</th></tr></thead><tbody>{{range .Attachments}}<tr><td><code>{{.ID}}</code></td><td>{{(index $.Gateways .GatewayID).Name}}</td><td>{{(index $.Agents .AgentID).Name}}</td><td>{{.Enabled}}</td><td><form class="inline" method="post" action="/admin/attachments/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>Toggle</button></form></td></tr>{{else}}<tr><td colspan="5">No combinations</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/attachments"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Gateway<select name="gateway_id" required>{{range .Gateways}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><label>Agent<select name="agent_id" required>{{range .Agents}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><button>Create combination</button></form></section>

<section><h2>Links</h2><table><thead><tr><th>Link</th><th>Route</th><th>Policy</th><th>Status</th><th>Action</th></tr></thead><tbody>{{range .Links}}{{$st := index $.LinkSummary .ID}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td><code>{{.URL}}</code><br>attachment {{short .AttachmentID}}</td><td><form method="post" action="/admin/links/{{.ID}}/policy"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="number" name="priority" value="{{.Priority}}" min="0" title="priority"><input type="number" name="weight" value="{{.Weight}}" min="1" title="weight"><input type="number" name="connections" value="{{.Connections}}" min="1" title="connections"><input type="number" name="max_streams" value="{{.MaxStreams}}" min="1" title="max streams"><button>Apply</button></form></td><td>online {{$st.Online}}, ready {{$st.Ready}}<br>connections {{$st.Connections}}, streams {{$st.ActiveStreams}}, RTT {{$st.RTTMillis}} ms<br>↑ {{$st.UploadBytes}} ↓ {{$st.DownloadBytes}}<br><span class="error">{{$st.LastError}}</span></td><td>enabled {{.Enabled}}<br><form class="inline" method="post" action="/admin/links/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>Toggle</button></form></td></tr>{{else}}<tr><td colspan="5">No links</td></tr>{{end}}</tbody></table>
<h3>Per-node reports</h3><table><thead><tr><th>Link</th><th>Reporter</th><th>Connections</th><th>Last result</th></tr></thead><tbody>{{range .LinkReports}}<tr><td><code>{{short .LinkID}}</code></td><td><code>{{short .ReporterNodeID}}</code></td><td>{{.Connections}} / streams {{.ActiveStreams}}</td><td>{{.LastSeen}}<br><span class="error">{{.LastError}}</span></td></tr>{{else}}<tr><td colspan="4">No runtime reports</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/links"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Node<select name="attachment_id" required>{{range .Attachments}}<option value="{{.ID}}">{{short .ID}}</option>{{end}}</select></label><label>Name<input name="name" required></label><label>WSS URL<input name="url" placeholder="wss://gateway.example/tunnel" required></label><label>HTTP Host<input name="http_host"></label><label>TLS server name<input name="tls_server_name"></label><label>TLS verify<input type="checkbox" name="tls_verify" checked></label><label>Priority<input type="number" name="priority" value="10" min="0"></label><label>Weight<input type="number" name="weight" value="1" min="1"></label><label>Connections<input type="number" name="connections" value="2" min="1"></label><label>Max streams/session<input type="number" name="max_streams" value="256" min="1"></label><button>Create link</button></form></section>

<section><h2>User grants</h2><table><thead><tr><th>Grant</th><th>User</th><th>Node</th><th>State</th><th>Traffic / connections</th><th>Action</th></tr></thead><tbody>{{range .Grants}}{{$st := index $.GrantSummary .ID}}<tr><td><code>{{.ID}}</code><br>UUID {{.VMessUUID}}</td><td>{{(index $.Users .UserID).Name}}</td><td><code>{{short .AttachmentID}}</code></td><td>enabled {{.Enabled}}<br>published {{.Published}}</td><td>↑ {{$st.UploadBytes}} ↓ {{$st.DownloadBytes}}<br>TCP {{$st.TCPConnections}}, UDP {{$st.UDPAssociations}}</td><td><form class="inline" method="post" action="/admin/grants/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>Toggle</button></form></td></tr>{{else}}<tr><td colspan="6">No grants</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/grants"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>User<select name="user_id" required>{{range .Users}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><label>Node<select name="attachment_id" required>{{range .Attachments}}<option value="{{.ID}}">{{short .ID}}</option>{{end}}</select></label><button>Create grant</button></form></section>

<section><h2>Install nodes</h2><p class="muted">Commands contain a one-time credential and are intentionally never stored in the public repository.</p><form class="stack" method="post" action="/admin/enrollments"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Role<select name="role"><option value="gateway">Gateway</option><option value="agent">Agent</option></select></label><label>Node<select name="node_id" required><optgroup label="Gateways">{{range .Gateways}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</optgroup><optgroup label="Agents">{{range .Agents}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</optgroup></select></label><button>Generate one-time install command</button></form></section>

</div></main></body></html>{{end}}`
