package controller

import _ "embed"

//go:embed panel.css
var panelModernCSS string

const panelCSS = `
:root{font-family:ui-sans-serif,system-ui,sans-serif;color:#18202a;background:#f4f6f8}*{box-sizing:border-box}
body{margin:0}header{display:flex;align-items:center;justify-content:space-between;padding:18px 28px;background:#17212b;color:#fff}
main{max-width:1400px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:minmax(0,1fr);gap:20px}
section{background:#fff;border:1px solid #dce2e8;border-radius:8px;padding:18px;overflow:auto}h1,h2{margin:0 0 14px}h1{font-size:22px}h2{font-size:18px}
table{border-collapse:collapse;width:100%;font-size:13px}th,td{border-bottom:1px solid #e7ebef;padding:8px;text-align:left;vertical-align:top}th{color:#52606d}
form.inline{display:inline}form.stack{display:grid;grid-template-columns:repeat(2,minmax(120px,1fr));gap:8px;margin-top:14px}form.stack button{grid-column:1/-1}details{min-width:220px;margin-top:8px}details form{display:grid;gap:6px;margin:8px 0}summary{cursor:pointer;color:#1463d6}.danger{background:#b42318;border-color:#b42318}small{display:block;color:#687784;margin:6px 0}@media(max-width:600px){main{padding:10px}section{padding:10px}form.stack{grid-template-columns:minmax(0,1fr)}}
label{display:grid;gap:4px;font-size:12px;color:#52606d}input,select,button{font:inherit;padding:8px;border:1px solid #b9c3cc;border-radius:5px;background:#fff}button{cursor:pointer;background:#1463d6;color:#fff;border-color:#1463d6}.muted{color:#687784}.error{color:#b42318}.ok{color:#087443}.login{max-width:360px;margin:15vh auto;background:#fff;padding:28px;border-radius:8px}.login form{display:grid;gap:14px}code{word-break:break-all}
`

var panelTemplate = `{{define "panel"}}<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>xmesh panel</title><style>` + panelCSS + panelModernCSS + `</style><script src="/assets/panel.js" defer></script></head><body>
<header><a class="brand" href="#overview">◈ <strong>XMesh</strong><span>CONTROL CENTER</span></a><h1 class="sr-only">xmesh control panel</h1><form class="inline" method="post" action="/logout"><button>Sign out</button></form></header>
<nav class="sidebar" aria-label="Main navigation"><a href="#overview">◉ <span>总览</span></a><a href="#network">⌘ <span>节点与线路</span></a><a href="#users">♙ <span>用户与订阅</span></a><a href="#deploy">↗ <span>部署向导</span></a><a href="#maintenance">⚙ <span>系统维护</span></a><p>Gateway → Agent<br>连接状态 · 配置 · 订阅</p></nav>
<main><div class="page-heading"><div><p class="eyebrow">XMESH / WORKSPACE</p><h1 id="page-title">总览</h1><p class="muted" id="page-description">查看网络健康状况与需要处理的事项。</p></div><div class="refresh-tools"><button type="button" id="refresh-status">Refresh status</button><span id="refresh-note" role="status">正在获取状态…</span></div></div>
<div id="notice" role="status">{{if .Notice}}{{.Notice}}{{end}}</div><noscript><p>启用 JavaScript 可使用拓扑、筛选及局部刷新。下方基础管理表单仍可使用。</p></noscript><div class="grid">
<section id="overview" data-page="overview"><div id="metrics" class="metrics"><p>正在加载网络状态…</p></div></section>
<section id="network-map" data-page="overview"><div class="section-heading"><div><h2>网络连接</h2><p class="muted">选择节点或线路查看详情。可用状态要求两端配置和链路均就绪。</p></div><div class="segmented"><button type="button" data-view="topology" aria-pressed="true">拓扑</button><button type="button" data-view="matrix" aria-pressed="false">矩阵</button></div></div><div class="toolbar"><label>搜索节点<input id="map-search" type="search" placeholder="名称或地址"></label><label>线路状态<select id="map-state"><option value="all">全部状态</option><option value="ready">可用</option><option value="pending">待就绪</option><option value="offline">离线</option><option value="disabled">停用</option></select></label></div><div id="topology"></div><div id="matrix" hidden></div><p class="legend">● 可用　◐ 待就绪　○ 离线　— 停用 · Agent 主动建立隧道</p></section>
<section id="attention" data-page="overview"><h2>需要处理</h2><div id="todo-list" class="todo-list"></div></section>
<section id="trends" data-page="overview"><div class="section-heading"><div><h2>链路趋势</h2><p class="muted">最近 24 小时 · 每 5 分钟采样 · Gateway 单端统计</p></div><label>链路<select id="history-link" aria-label="历史链路"></select></label></div><div id="history-chart"></div><div id="rankings"></div></section>
<section id="wizard" data-page="deploy"><p class="eyebrow">GUIDED SETUP</p><h2>从节点到可用订阅</h2><p>新建线路会同时创建 Gateway、Agent 和关联。已有节点可直接复用，系统补齐绑定与 Link。</p><ol class="wizard-steps"><li><a href="#create-route">1. 新建线路</a> / <a href="#assign">复用节点</a></li><li><a href="#quick-install">2. 执行安装</a></li><li><a href="#readiness">3. 检查就绪</a></li><li><a href="#subscribe">4. 开通订阅</a></li></ol><div id="deployment-progress"></div></section>
<section id="activity" data-page="maintenance"><h2>操作记录</h2><p class="muted">最近 100 次管理请求的执行结果。节点就绪与升级完成情况会单独跟踪。</p><div id="upgrade-progress"></div><div id="operation-list"></div></section>
<section id="release" data-page="maintenance"><h2>Deployment · 1. Release sources</h2><p>Version <code>{{.Release.Version}}</code>. GitHub: <code>{{.Release.GitHubURL}}</code></p><p>Controller mirror: <code>{{.Release.LocalURL}}</code> · fully cached {{.Release.Ready}}</p><p class="muted">The Controller fetches each asset from GitHub on its first download request, checks SHA256SUMS, and keeps it on disk for later nodes. No release binaries are embedded in the Controller.</p><table><thead><tr><th>Asset</th><th>Cached and verified</th></tr></thead><tbody>{{range .Release.Assets}}<tr><td><a href="{{$.Release.LocalURL}}/{{.Name}}">{{.Name}}</a></td><td>{{.Ready}}</td></tr>{{end}}</tbody></table>{{if not .Release.Enabled}}<p class="error">Set release_dir, release_base_url (HTTPS) and release_version in Controller configuration to enable caching.</p>{{end}}</section>

<section id="create-route" data-page="deploy"><h2>Deployment · 2. Create route</h2><p class="muted">For REALITY, use the Gateway IP in the Link URL and a reachable HTTPS site as target. Gateway REALITY listens on port 8443 by default. Legacy WSS remains supported.</p><form class="stack" method="post" action="/admin/quick-setup"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Gateway name<input name="gateway_name" required></label><label>Agent name<input name="agent_name" required></label><label>Gateway public host<input name="public_host" placeholder="gateway.example.com" required></label><label>VMess port<input type="number" name="vmess_port" value="8080" min="1" max="65535" required></label><label>VMess WS path<input name="vmess_path" value="/proxy" required></label><label>VMess HTTP Host<input name="vmess_host"></label><label>Agent allowed CIDRs<input name="allowed_cidrs" value="0.0.0.0/0, ::/0" required></label><label>Agent denied CIDRs<input name="denied_cidrs" placeholder="169.254.0.0/16"></label><label>Agent → Gateway Link URL<input name="link_url" placeholder="reality://203.0.113.10:8443/tunnel" required></label><label>REALITY target (for reality://)<input name="reality_target" placeholder="example.com:443"></label><label>Link HTTP Host<input name="link_http_host"></label><label>Link TLS server name (legacy WSS)<input name="tls_server_name"></label><button>Create route</button></form></section>

<section id="readiness" data-page="deploy"><h2>Deployment · 3. Check readiness</h2><p class="muted">Each stage points to the next check. "Online" is not the same as a usable Link.</p><table><thead><tr><th>Node</th><th>Version</th><th>Identity</th><th>Online</th><th>Config applied</th><th>Runtime ready</th><th>Next action</th></tr></thead><tbody>{{range .Deployments}}<tr><td>{{.Role}} {{.Name}}<br><code>{{.ID}}</code></td><td>{{.Version}}</td><td>{{.Identity}}</td><td>{{.Online}}</td><td>{{.Applied}}</td><td>{{.Runtime}}</td><td>{{.Next}}</td></tr>{{else}}<tr><td colspan="7">Create a Gateway or Agent to begin.</td></tr>{{end}}</tbody></table></section>

<section id="users" data-page="users"><h2>Users</h2><table><thead><tr><th>User</th><th>Enabled</th><th>Subscription</th><th>Action</th></tr></thead><tbody>{{range .UserList}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td>{{.Enabled}}</td><td><code>{{$.PublicURL}}/subscription/{{.SubscriptionToken}}</code></td><td><form class="inline" method="post" action="/admin/users/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>{{if .Enabled}}Disable{{else}}Enable{{end}}</button></form> <form class="inline" method="post" action="/admin/users/{{.ID}}/reset-subscription"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>Reset link</button></form></td></tr>{{else}}<tr><td colspan="4">No users</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/users"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Name<input name="name" required></label><button>Create user</button></form></section>

<section id="gateways" data-page="network"><h2>Gateways</h2><table><thead><tr><th>Gateway</th><th>VMess WS</th><th>Config</th><th>Runtime</th><th>Action</th></tr></thead><tbody>{{range .GatewayList}}{{$st := index $.NodeStatus .ID}}{{$impact := index $.NodeImpacts .ID}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td>{{.PublicHost}}:{{.VMessPort}}{{.VMessPath}}<br>TLS off</td><td>enabled {{.Enabled}}<br>desired {{.DesiredVersion}}<br>{{status $st.AppliedVersion .DesiredVersion $st.ApplyError}}<br>Xray ready: {{$st.XrayReady}}</td><td>online {{$st.Online}}, ready {{$st.Ready}}<br>tunnels {{$st.TunnelConnections}}, TCP {{$st.TCPConnections}}, UDP {{$st.UDPAssociations}}<br><span class="error">{{$st.LastError}}</span></td><td><form class="inline" method="post" action="/admin/gateways/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>{{if .Enabled}}Disable{{else}}Enable{{end}}</button></form><details><summary>Edit / Delete</summary><form method="post" action="/admin/gateways/{{.ID}}/edit"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>Name<input name="name" value="{{.Name}}" required></label><label>Public host<input name="public_host" value="{{.PublicHost}}" required></label><label>VMess port<input type="number" name="vmess_port" value="{{.VMessPort}}" min="1" max="65535" required></label><label>WS path<input name="vmess_path" value="{{.VMessPath}}" required></label><label>HTTP Host<input name="vmess_host" value="{{.VMessHost}}"></label><button>Save</button></form><small>Access changes are published after this Gateway reports the new config applied. Auto-generated REALITY Link addresses follow Public host changes.</small><p>Delete impact: {{$impact.Assignments}} assignments, {{$impact.Links}} Links, {{$impact.Grants}} grants for {{$impact.Users}} users.</p><form method="post" action="/admin/gateways/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>Type gateway name to delete<input name="confirm_name" required autocomplete="off"></label><button class="danger">Delete gateway and its routes</button></form><small>Stop the installed node separately.</small></details></td></tr>{{else}}<tr><td colspan="5">No gateways</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/gateways"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Name<input name="name" required></label><label>Public host<input name="public_host" required></label><label>VMess port<input type="number" name="vmess_port" value="8080" min="1" max="65535"></label><label>WS path<input name="vmess_path" value="/proxy"></label><label>HTTP Host<input name="vmess_host"></label><button>Create gateway</button></form></section>

<section id="agents" data-page="network"><h2>Agents</h2><table><thead><tr><th>Agent</th><th>Config</th><th>Runtime</th><th>Action</th></tr></thead><tbody>{{range .AgentList}}{{$st := index $.NodeStatus .ID}}{{$impact := index $.NodeImpacts .ID}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td>enabled {{.Enabled}}<br>desired {{.DesiredVersion}}<br>{{status $st.AppliedVersion .DesiredVersion $st.ApplyError}}</td><td>online {{$st.Online}}, ready {{$st.Ready}}<br>tunnels {{$st.TunnelConnections}}, TCP {{$st.TCPConnections}}, UDP {{$st.UDPAssociations}}<br><span class="error">{{$st.LastError}}</span></td><td><form class="inline" method="post" action="/admin/agents/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>{{if .Enabled}}Disable{{else}}Enable{{end}}</button></form><details><summary>Edit / Delete</summary><form method="post" action="/admin/agents/{{.ID}}/edit"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>Name<input name="name" value="{{.Name}}" required></label><label>Allowed CIDRs<input name="allowed_cidrs" value="{{join .AllowedCIDRs}}" required></label><label>Denied CIDRs<input name="denied_cidrs" value="{{join .DeniedCIDRs}}"></label><button>Save</button></form><p>Delete impact: {{$impact.Assignments}} assignments, {{$impact.Links}} Links, {{$impact.Grants}} grants for {{$impact.Users}} users.</p><form method="post" action="/admin/agents/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>Type agent name to delete<input name="confirm_name" required autocomplete="off"></label><button class="danger">Delete agent and its routes</button></form><small>Stop the installed node separately.</small></details></td></tr>{{else}}<tr><td colspan="4">No agents</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/agents"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Name<input name="name" required></label><label>Allowed CIDRs<input name="allowed_cidrs" value="0.0.0.0/0, ::/0" required></label><label>Denied CIDRs<input name="denied_cidrs" placeholder="169.254.0.0/16"></label><button>Create agent</button></form></section>

<section id="assignments" data-page="network"><h2>Gateway × Agent nodes</h2><table><thead><tr><th>Node ID</th><th>Gateway</th><th>Agent</th><th>Enabled</th><th>Action</th></tr></thead><tbody>{{range .AttachmentList}}{{$impact := index $.RouteImpacts .ID}}<tr><td><code>{{.ID}}</code></td><td>{{(index $.Gateways .GatewayID).Name}}</td><td>{{(index $.Agents .AgentID).Name}}</td><td>{{.Enabled}}</td><td><form class="inline" method="post" action="/admin/attachments/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>{{if .Enabled}}Disable{{else}}Enable{{end}}</button></form><details><summary>Delete</summary><p>Removes {{$impact.Links}} Links and {{$impact.Grants}} grants for {{$impact.Users}} users.</p><form method="post" action="/admin/attachments/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>Type node ID to delete<input name="confirm_id" required autocomplete="off"></label><button class="danger">Delete assignment</button></form></details></td></tr>{{else}}<tr><td colspan="5">No combinations</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/attachments"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Gateway<select name="gateway_id" required>{{range .GatewayList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><label>Agent<select name="agent_id" required>{{range .AgentList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><button>Create combination</button></form></section>

<section id="links" data-page="network"><h2>Links</h2><table><thead><tr><th>Link</th><th>Route</th><th>Policy</th><th>Status</th><th>Action</th></tr></thead><tbody>{{range .LinkList}}{{$st := index $.LinkSummary .ID}}{{$route := index $.Attachments .AttachmentID}}{{$gw := index $.Gateways $route.GatewayID}}<tr><td>{{.Name}}<br><code>{{.ID}}</code></td><td><code>{{.URL}}</code><br>attachment {{short .AttachmentID}}</td><td><form method="post" action="/admin/links/{{.ID}}/policy"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="number" name="priority" value="{{.Priority}}" min="0" title="priority"><input type="number" name="weight" value="{{.Weight}}" min="1" title="weight"><input type="number" name="connections" value="{{.Connections}}" min="1" title="connections"><input type="number" name="max_streams" value="{{.MaxStreams}}" min="1" title="max streams"><button>Apply</button></form></td><td>online {{$st.Online}}, ready {{$st.Ready}}<br>connections {{$st.Connections}}, streams {{$st.ActiveStreams}}, RTT {{$st.RTTMillis}} ms<br>write stalls {{$st.WriteStalls}}, blocked {{$st.WriteBlockedMillis}} ms, rejects {{$st.QueueDrops}}<br>↑ {{$st.UploadBytes}} ↓ {{$st.DownloadBytes}}<br><span class="error">{{$st.LastError}}</span></td><td>enabled {{.Enabled}}<br><form class="inline" method="post" action="/admin/links/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>{{if .Enabled}}Disable{{else}}Enable{{end}}</button></form><details><summary>Edit / Delete</summary><form method="post" action="/admin/links/{{.ID}}/edit"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>Name<input name="name" value="{{.Name}}" required></label><label>Link URL<input name="url" value="{{.URL}}" required></label><label>REALITY target (shared by Gateway)<input name="reality_target" value="{{$gw.RealityTarget}}"></label><label>HTTP Host<input name="http_host" value="{{.HTTPHost}}"></label><label>TLS server name (legacy WSS)<input name="tls_server_name" value="{{.TLSServerName}}"></label><label>TLS verify (legacy WSS)<input type="checkbox" name="tls_verify" {{if .TLSVerify}}checked{{end}}></label><button>Save Link</button></form><small>Changing the shared REALITY target updates every Link on this Gateway after nodes apply.</small><form method="post" action="/admin/links/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>Type Link name to delete<input name="confirm_name" required autocomplete="off"></label><button class="danger">Delete Link</button></form></details></td></tr>{{else}}<tr><td colspan="5">No links</td></tr>{{end}}</tbody></table>
<h3>Per-node reports</h3><table><thead><tr><th>Link</th><th>Reporter</th><th>Connections</th><th>Last result</th></tr></thead><tbody>{{range .LinkReports}}<tr><td><code>{{short .LinkID}}</code></td><td><code>{{short .ReporterNodeID}}</code></td><td>{{.Connections}} / streams {{.ActiveStreams}}</td><td>{{.LastSeen}}<br><span class="error">{{.LastError}}</span></td></tr>{{else}}<tr><td colspan="4">No runtime reports</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/links"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Node<select name="attachment_id" required>{{range .AttachmentList}}<option value="{{.ID}}">{{(index $.Gateways .GatewayID).Name}} / {{(index $.Agents .AgentID).Name}}</option>{{end}}</select></label><label>Name<input name="name" required></label><label>Link URL<input name="url" placeholder="reality://203.0.113.10:8443/tunnel" required></label><label>REALITY target (for reality://)<input name="reality_target" placeholder="example.com:443"></label><label>HTTP Host<input name="http_host"></label><label>TLS server name (legacy WSS)<input name="tls_server_name"></label><label>TLS verify (legacy WSS)<input type="checkbox" name="tls_verify" checked></label><label>Priority<input type="number" name="priority" value="10" min="0"></label><label>Weight<input type="number" name="weight" value="1" min="1"></label><label>Connections<input type="number" name="connections" value="2" min="1"></label><label>Max streams/session<input type="number" name="max_streams" value="256" min="1"></label><button>Create link</button></form></section>

<section id="grants" data-page="users"><h2>User grants</h2><table><thead><tr><th>Grant</th><th>User</th><th>Node</th><th>State</th><th>Traffic / connections</th><th>Action</th></tr></thead><tbody>{{range .GrantList}}{{$st := index $.GrantSummary .ID}}<tr><td><code>{{.ID}}</code><br>UUID {{.VMessUUID}}</td><td>{{(index $.Users .UserID).Name}}</td><td><code>{{short .AttachmentID}}</code></td><td>enabled {{.Enabled}}<br>published {{.Published}}</td><td>↑ {{$st.UploadBytes}} ↓ {{$st.DownloadBytes}}<br>TCP {{$st.TCPConnections}}, UDP {{$st.UDPAssociations}}</td><td><form class="inline" method="post" action="/admin/grants/{{.ID}}/toggle"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>{{if .Enabled}}Disable{{else}}Enable{{end}}</button></form><details><summary>Delete</summary><form method="post" action="/admin/grants/{{.ID}}/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><label>Type grant ID to delete<input name="confirm_id" required autocomplete="off"></label><button class="danger">Delete grant</button></form></details></td></tr>{{else}}<tr><td colspan="6">No grants</td></tr>{{end}}</tbody></table>
<form class="stack" method="post" action="/admin/grants"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>User<select name="user_id" required>{{range .UserList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><label>Node<select name="attachment_id" required>{{range .AttachmentList}}<option value="{{.ID}}">{{(index $.Gateways .GatewayID).Name}} / {{(index $.Agents .AgentID).Name}}</option>{{end}}</select></label><button>Create grant</button></form></section>

<section id="install" data-page="deploy"><h2>Deployment · 3. Install nodes</h2><p class="muted">Generate separately for each node. The one-time token is shown once, expires in 30 minutes, and is entered at the host prompt. Generating again revokes the previous unused token for that node. Choose Controller mirror when GitHub is slow; either systemd or Docker Compose is available.</p><form class="stack" method="post" action="/admin/enrollments"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Role<select name="role"><option value="gateway">Gateway</option><option value="agent">Agent</option></select></label><label>Node<select name="node_id" required><optgroup label="Gateways">{{range .GatewayList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</optgroup><optgroup label="Agents">{{range .AgentList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</optgroup></select></label><button>Generate installation options</button></form><h3>Recent enrollment tokens</h3><table><thead><tr><th>Node</th><th>State</th><th>Expires</th><th>Action</th></tr></thead><tbody>{{range .Enrollments}}<tr><td>{{.Role}} <code>{{.NodeID}}</code></td><td>{{.State}}</td><td>{{.ExpiresAt}}</td><td>{{if eq .State "active"}}<form class="inline" method="post" action="/admin/enrollments/{{.ID}}/revoke"><input type="hidden" name="csrf" value="{{$.CSRF}}"><button>Revoke</button></form>{{end}}</td></tr>{{else}}<tr><td colspan="4">No tokens generated.</td></tr>{{end}}</tbody></table></section>

<section id="quick-install" data-page="deploy"><h2>Quick node installation</h2><p class="muted">Create a Gateway or Agent above, then generate its own verified installer. Run the command on that host and enter the one-time token at its prompt. A node can be installed before any Link exists.</p>{{range .GatewayList}}<form class="inline" method="post" action="/admin/enrollments"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="role" value="gateway"><input type="hidden" name="node_id" value="{{.ID}}"><button>Install Gateway: {{.Name}}</button></form> {{end}}{{range .AgentList}}<form class="inline" method="post" action="/admin/enrollments"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="role" value="agent"><input type="hidden" name="node_id" value="{{.ID}}"><button>Install Agent: {{.Name}}</button></form> {{end}}</section>

<section id="assign" data-page="deploy"><h2>Assign multiple Gateways to an Agent</h2><p class="muted">Select the Gateways to connect. Existing assignments are kept. New REALITY Links use port 8443 and the Gateway's existing target, or the target entered below for a new Gateway.</p><form class="stack" method="post" action="/admin/assign-gateways"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Agent<select name="agent_id" required>{{range .AgentList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><fieldset><legend>Gateways</legend>{{range .GatewayList}}<label><input type="checkbox" name="gateway_id" value="{{.ID}}">{{.Name}} ({{.PublicHost}})</label>{{end}}</fieldset><label>REALITY target for new Gateways<input name="reality_target" placeholder="your-tls13-host.example:443"></label><button>Assign selected Gateways</button></form></section>

<section id="subscribe" data-page="users"><h2>Open VMess/WS subscription</h2><p class="muted">选择要新增或重新启用的线路。清除选择不会撤销已有授权；撤销请在授权管理中操作。Gateway 应用配置后自动发布订阅。</p><form class="stack" method="post" action="/admin/subscribe"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>User<select name="user_id" required>{{range .UserList}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><fieldset><legend>Gateway / Agent routes</legend>{{range .AttachmentList}}<label><input type="checkbox" name="attachment_id" value="{{.ID}}">{{(index $.Gateways .GatewayID).Name}} / {{(index $.Agents .AgentID).Name}}</label>{{end}}</fieldset><button>Open selected routes</button></form>{{range .UserList}}<p>{{.Name}} ({{index $.SubscriptionCounts .ID}}): <input aria-label="Subscription URL for {{.Name}}" value="{{$.PublicURL}}/subscription/{{.SubscriptionToken}}" readonly><button type="button" data-copy="{{$.PublicURL}}/subscription/{{.SubscriptionToken}}">Copy subscription</button></p>{{end}}</section>

<section id="upgrade" data-page="maintenance"><h2>Upgrade and backup</h2><p class="muted">Upgrade commands use the configured fixed release version and preserve node identity. Run them on the existing host; Docker upgrades roll back if the new container fails startup.</p><h3>Controller</h3>{{if .ControllerUpgrade.Ready}}<p>Current release: {{.Release.Version}}. Last upgrade: {{if .ControllerUpgrade.State}}{{.ControllerUpgrade.State}} {{.ControllerUpgrade.Version}} {{.ControllerUpgrade.At}}{{else}}none{{end}}.</p><form method="post" action="/admin/controller/upgrade-latest"><input type="hidden" name="csrf" value="{{.CSRF}}"><button{{if or (eq .ControllerUpgrade.State "queued") (eq .ControllerUpgrade.State "running")}} disabled{{end}}>Check GitHub and upgrade Controller to latest</button></form><p class="muted">The host updater verifies GitHub release checksums, backs up Controller state, and rolls back on startup failure. The panel briefly disconnects during upgrade.</p>{{else}}<p class="muted">One-click Controller upgrade requires a Docker installation with the host updater installed by v0.2.3 or later on a systemd host. Until then, run the verified installer on the Controller host.</p>{{end}}<p class="muted">Keep Controller backup archives off-host; they contain credentials.</p><h3>Nodes</h3>{{range .GatewayList}}<p><a href="/admin/upgrade/gateway/{{.ID}}">Upgrade Gateway: {{.Name}}</a></p>{{end}}{{range .AgentList}}<p><a href="/admin/upgrade/agent/{{.ID}}">Upgrade Agent: {{.Name}}</a></p>{{end}}</section>

</div></main><dialog id="detail-dialog"><div class="section-heading"><h2 id="detail-title">详情</h2><button type="button" id="close-detail">关闭</button></div><div id="detail-body"></div></dialog></body></html>{{end}}`
